### ISSUE TITLE
Pandas 2.0.3 crashing on all 3 major platforms

### ISSUE THREAD

**Issue by bashtage** [conda-forge/pandas-feedstock#180] opened 2023-09-27 12:14 UTC
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Seeing 
```
Traceback (most recent call last):
  File "/Users/runner/miniforge3/conda-bld/arch-py_1695814679546/test_tmp/run_test.py", line 2, in <module>
    import arch
  File "/Users/runner/miniforge3/conda-bld/arch-py_1695814679546/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/pypy3.9/site-packages/arch/__init__.py", line 2, in <module>
    from .univariate.mean import arch_model
  File "/Users/runner/miniforge3/conda-bld/arch-py_1695814679546/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/pypy3.9/site-packages/arch/univariate/__init__.py", line 5, in <module>
    from arch.univariate import recursions_python
  File "/Users/runner/miniforge3/conda-bld/arch-py_1695814679546/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/pypy3.9/site-packages/arch/univariate/recursions_python.py", line 9, in <module>
    from arch.compat.numba import jit
  File "/Users/runner/miniforge3/conda-bld/arch-py_1695814679546/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/pypy3.9/site-packages/arch/compat/numba.py", line 5, in <module>
    from arch.utility.exceptions import PerformanceWarning
  File "/Users/runner/miniforge3/conda-bld/arch-py_1695814679546/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/pypy3.9/site-packages/arch/utility/__init__.py", line 5, in <module>
    from arch.utility.cov import cov_nw
  File "/Users/runner/miniforge3/conda-bld/arch-py_1695814679546/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/pypy3.9/site-packages/arch/utility/cov.py", line 5, in <module>
    from arch.typing import Float64Array
  File "/Users/runner/miniforge3/conda-bld/arch-py_1695814679546/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/pypy3.9/site-packages/arch/typing.py", line 8, in <module>
    from pandas import DataFrame, Series, Timestamp
  File "/Users/runner/miniforge3/conda-bld/arch-py_1695814679546/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/pypy3.9/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import is_numpy_dev as _is_numpy_dev  # pyright: ignore # noqa:F401
  File "/Users/runner/miniforge3/conda-bld/arch-py_1695814679546/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/pypy3.9/site-packages/pandas/compat/__init__.py", line 25, in <module>
    from pandas.compat.numpy import (
  File "/Users/runner/miniforge3/conda-bld/arch-py_1695814679546/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/pypy3.9/site-packages/pandas/compat/numpy/__init__.py", line 4, in <module>
    from pandas.util.version import Version
  File "/Users/runner/miniforge3/conda-bld/arch-py_1695814679546/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/pypy3.9/site-packages/pandas/util/__init__.py", line 2, in <module>
    from pandas.util._decorators import (  # noqa:F401
  File "/Users/runner/miniforge3/conda-bld/arch-py_1695814679546/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/pypy3.9/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly
  File "/Users/runner/miniforge3/conda-bld/arch-py_1695814679546/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/lib/pypy3.9/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
TypeError: type 'cython_function_or_method' is not an acceptable base type
```

when importing pandas.  THis has affected the statsmodels feedstock and arch-py feedstock.

### Installed packages

```shell
libffi:                  3.4.2-h8ffe710_5            conda-forge
    libhwloc:                2.9.3-default_haede6df_1009 conda-forge
    libiconv:                1.17-h8ffe710_0             conda-forge
    liblapack:               3.9.0-18_win64_mkl          conda-forge
    libsqlite:               3.43.0-hcfcfb64_0           conda-forge
    libxml2:                 2.11.5-hc3477c8_1           conda-forge
    libzlib:                 1.2.13-hcfcfb64_5           conda-forge
    m2w64-gcc-libgfortran:   5.3.0-6                     conda-forge
    m2w64-gcc-libs:          5.3.0-7                     conda-forge
    m2w64-gcc-libs-core:     5.3.0-7                     conda-forge
    m2w64-gmp:               6.1.0-2                     conda-forge
    m2w64-libwinpthread-git: 5.0.0.4634.697f757-2        conda-forge
    mkl:                     2022.1.0-h6a75c08_874       conda-forge
    msys2-conda-epoch:       20160418-1                  conda-forge
    numpy:                   1.25.2-py39h821adfb_0       conda-forge
    openssl:                 3.1.3-hcfcfb64_0            conda-forge
    packaging:               23.1-pyhd8ed1ab_0           conda-forge
    pandas:                  2.0.3-py39haf6a60e_1        conda-forge
    patsy:                   0.5.3-pyhd8ed1ab_0          conda-forge
    pip:                     23.2.1-pyhd8ed1ab_0         conda-forge
    platformdirs:            3.10.0-pyhd8ed1ab_0         conda-forge
    pooch:                   1.7.0-pyha770c72_3          conda-forge
    pthreads-win32:          2.9.1-hfa6e2cd_3            conda-forge
    pypy3.9:                 7.3.12-h994e1e7_5           conda-forge
    pysocks:                 1.7.1-pyh0701188_6          conda-forge
    python:                  3.9.17-0_73_pypy            conda-forge
    python-dateutil:         2.8.2-pyhd8ed1ab_0          conda-forge
    python-tzdata:           2023.3-pyhd8ed1ab_0         conda-forge
    python_abi:              3.9-4_pypy39_pp73           conda-forge
    pytz:                    2023.3.post1-pyhd8ed1ab_0   conda-forge
    requests:                2.31.0-pyhd8ed1ab_0         conda-forge
    scipy:                   1.11.2-py39hbf2a3dc_0       conda-forge
    setuptools:              68.2.2-pyhd8ed1ab_0         conda-forge
    six:                     1.16.0-pyh6c4a22f_0         conda-forge
    sqlite:                  3.43.0-hcfcfb64_0           conda-forge
    statsmodels:             0.14.0-py39hea5744f_1       conda-forge
    tbb:                     2021.10.0-h91493d7_1        conda-forge
    tk:                      8.6.13-hcfcfb64_0           conda-forge
    typing-extensions:       4.8.0-hd8ed1ab_0            conda-forge
    typing_extensions:       4.8.0-pyha770c72_0          conda-forge
    tzdata:                  2023c-h71feb2d_0            conda-forge
    ucrt:                    10.0.22621.0-h57928b3_0     conda-forge
    urllib3:                 2.0.5-pyhd8ed1ab_0          conda-forge
    vc:                      14.3-h64f974e_17            conda-forge
    vc14_runtime:            14.36.32532-hdcecf7f_17     conda-forge
    vs2015_runtime:          14.36.32532-h05e6639_17     conda-forge
    wheel:                   0.41.2-pyhd8ed1ab_0         conda-forge
    win_inet_pton:           1.1.0-pyhd8ed1ab_6          conda-forge
    xz:                      5.2.6-h8d14728_0            conda-forge
    zlib:                    1.2.13-hcfcfb64_5           conda-forge

```
```


### Environment info

```shell
Log example here:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=789882&view=logs&jobId=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&j=5be07ae1-d8ba-5406-47b6-8e3a3a12f825&t=c94d5231-acfc-5e67-dafc-77bdd383ead4
```

**Comment by lithomas1** [comment] 2023-09-29 18:17
This is a duplicate of #176.

**Closed by lithomas1** 2023-09-29 18:17 UTC
Labels: bug
